---
collections:
  - name: https://opendev.org/openstack/ansible-config_template
    version: master
    type: git
  - name: https://github.com/ansible-collections/community.general
    type: git
    version: main
