---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    force: ${GALAXY_FORCE:-false}

driver:
  name: docker

platforms:
  - name: "systemd-mount-${MOLECULE_SCENARIO_NAME}"
    image: "${DOCKER_REGISTRY:-quay.io/gotmax23}/${DOCKER_IMAGE_TAG:-debian-systemd:bookworm}"
    command: ${DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    systemd: true
    groups:
      - mount_hosts
    volumes:
      - /tmp/systemd_mount_nfs:/srv/nfs/test:rw

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../../tests/prepare.yml
    converge: ../../tests/test.yml
    verify: ../../tests/verify.yml
  config_options:
    defaults:
      inject_facts_as_vars: false

scenario:
  name: default
